//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SZWALNIA
{
    using System;
    using System.Collections.Generic;
    
    public partial class vMaszyny_serwis
    {
        public int ID_Maszyny { get; set; }
        public string Producent { get; set; }
        public string Nazwa { get; set; }
        public int Resurs_Rbh { get; set; }
        public int Serwis_Co_Ile { get; set; }
        public string Numer_seryjny { get; set; }
    }
}
